name: pipeline do python

on:
  push:
    branches: [main]

jobs:
  linter:
    name: Análise de Código (Linter)
    runs-on: ubuntu-latest
    steps:
      - name: baixar código repositorio
        uses: actions/checkout@v4
      - name: configurar python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: instalar linter
        run: pip install flake8
      - name: Executar Linter
        run: flake8 calculadora.py test_calculadora.py --count --show-source --statistics

  seguranca:
    name: Análise de Segurança
    runs-on: ubuntu-latest
    steps:
      - name: baixar código repositorio
        uses: actions/checkout@v4
      - name: configurar python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: instalar bandit
        run: pip install bandit
      - name: Executar Análise de Segurança
        run: bandit -r calculadora.py


  build:
      name: realização do build
      runs-on: ubuntu-latest
      steps:
      - name: gerar artefato ZIP
        run: zip -r pipeline-demo.zip .
      - name: publicar artefato
        uses: actions/upload-artifact@v3
        with:
          name: codigo-buildado
          path: pipeline-demo.zip


  testes:
    name: Testes Unitários (Python ${{ matrix.python-version }} - ${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04]
        python-version: ["3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: baixar código repositorio
        uses: actions/checkout@v4
      - name: configurar python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with: 
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: instalar dependências
        run: pip install -r requirements.txt
      - name: Executar todos os testes unitários
        run: pytest test_calculadora.py
      - name: Baixar artefato
        uses: actions/download-artifact@v3
        with: name:codigo-buildado
      - name: extrair artefato
        run: unzip pipeline-demo.zip

  teste_soma:
    name: Teste de Soma
    runs-on: ubuntu-latest
    steps:
      - name: baixar código repositorio
        uses: actions/checkout@v4
      - name: configurar python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: instalar dependências
        run: pip install pytest
      - name: Executar teste de soma
        run: pytest test_calculadora.py::test_soma

  teste_subtracao:
    name: Teste de subtracao
    runs-on: ubuntu-latest
    steps:
      - name: baixar código repositorio
        uses: actions/checkout@v4
      - name: configurar python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: instalar dependências
        run: pip install pytest
      - name: Executar teste de subtracao
        run: pytest test_calculadora.py::test_subtracao

  teste_multiplicacao:
    name: Teste de multiplicacao
    runs-on: ubuntu-latest
    steps:
      - name: baixar código repositorio
        uses: actions/checkout@v4
      - name: configurar python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: instalar dependências
        run: pip install pytest
      - name: Executar teste de multiplicacao
        run: pytest test_calculadora.py::test_multiplicacao

  teste_divisao:
    name: Teste de divisao
    runs-on: ubuntu-latest
    steps:
      - name: baixar código repositorio
        uses: actions/checkout@v4
      - name: configurar python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: instalar dependências
        run: pip install pytest
      - name: Executar teste de divisao
        run: pytest test_calculadora.py::test_divisao

  cobertura:
    name: Cobertura de Código
    runs-on: ubuntu-latest
    steps:
      - name: baixar código repositorio
        uses: actions/checkout@v4
      - name: configurar python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: instalar dependências
        run: pip install pytest pytest-cov
      - name: Executar Análise de Cobertura
        run: pytest --cov=calculadora --cov-report=xml --cov-report=term-missing --cov-fail-under=80 test_calculadora.py
      - name: Análise com SonarQube
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Simular Deploy
    needs: [linter, seguranca, testes, teste_soma, teste_subtracao, teste_multiplicacao, teste_divisao, cobertura] 
    runs-on: ubuntu-latest
    steps:
      - name: Confirmar Deploy
        run: echo "Todos os testes individuais, a matriz, cobertura, linter e segurança passaram! Deploy realizado com sucesso."